//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyx264CoderGUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Easyx264CoderGUI.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetWorkingDir(&quot;$avisynth_plugin$&quot;)
        ///LoadPlugin(&quot;ffms2.dll&quot;)     #加载FFmpegSource挂载方式
        ///LoadPlugin(&quot;LSMASHSource.dll&quot;) #LWLibavVideoSource挂载方式
        ///#LWLibavVideoSource(&quot;$InputVedio$&quot;)
        ///FFVideoSource(&quot;$InputVedio$&quot;)
        ///ChangeFPS(25)
        ///ConvertToYV12().
        /// </summary>
        internal static string Avs25fps {
            get {
                return ResourceManager.GetString("Avs25fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetWorkingDir(&quot;$avisynth_plugin$&quot;)
        ///LoadPlugin(&quot;ffms2.dll&quot;)     #加载FFmpegSource挂载方式
        ///LoadPlugin(&quot;LSMASHSource.dll&quot;) #LWLibavVideoSource挂载方式
        ///LoadPlugin(&quot;VSFilter.dll&quot;)     #加载字幕插件
        ///Load_Stdcall_Plugin(&quot;yadif.dll&quot;)     #Yadif反交错滤镜
        ///LoadPlugin(&quot;nnedi3-0.9.4\nnedi3.dll&quot;)
        ///LoadPlugin(&quot;RemoveGrain-1.0\RemoveGrainSSE3.dll&quot;)
        ///LoadPlugin(&quot;RemoveGrain-1.0\RepairSSE3.dll&quot;)
        ///LoadPlugin(&quot;FluxSmooth-1.1a\FluxSmooth.dll&quot;)
        ///LoadPlugin(&quot;FFT3dGPU.dll&quot;)
        ///LoadPlugin(&quot;dither-1.23.0\avstp.dll&quot;)
        ///LoadPlugin(&quot;SmoothAdjust-v2.80\a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvsQTGMC {
            get {
                return ResourceManager.GetString("AvsQTGMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetWorkingDir(&quot;$avspluginpath$&quot;)
        ///
        ///LoadPlugin(&quot;dither-1.23.0\avstp.dll&quot;)
        ///LoadPlugin(&quot;SmoothAdjust-v2.80\avs-2.6.x\x86\SmoothAdjust.dll&quot;)
        ///LoadPlugin(&quot;masktools-26-for-2.6alpha4\mt_masktools-26.dll&quot;)
        ///LoadPlugin(&quot;nnedi3-0.9.4\nnedi3.dll&quot;)
        ///Import(&quot;masktools-v2.0a48\masktools\LimitedSharpenFaster.avsi&quot;)
        ///Import(&quot;masktools-v2.0a48\masktools\mfToon-v0.54.avsi&quot;)
        ///Import(&quot;masktools-v2.0a48\masktools\vmToon-v0.74.avsi&quot;)
        ///LoadPlugin(&quot;dither-1.23.0\dither.dll&quot;)
        ///Import(&quot;dither-1.23.0\dither.avsi&quot;)
        ///Import(&quot;O16mod_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvsScriptTemplete {
            get {
                return ResourceManager.GetString("AvsScriptTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --demuxer lavf --input-range pc --range pc    --bframes 9 --qcomp 0.60  --direct auto  --me umh   --psy-rd 0.40:0.00  --aq-strength 0.8  .
        /// </summary>
        internal static string TempleteGamei444 {
            get {
                return ResourceManager.GetString("TempleteGamei444", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --demuxer lavf  --qcomp 0.80 --direct auto  --me umh   --aq-strength 0.8 .
        /// </summary>
        internal static string TempleteHDi420 {
            get {
                return ResourceManager.GetString("TempleteHDi420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --demuxer lavf  --no-mbtree.
        /// </summary>
        internal static string TempleteOnline {
            get {
                return ResourceManager.GetString("TempleteOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --acodec $acodec$ --output-csp $csp$ $profile$   $crf$  --preset $preset$  $tune$  $resize$    $userargs$   -o  &quot;$outputfile$&quot; &quot;$input$&quot;.
        /// </summary>
        internal static string x264Line {
            get {
                return ResourceManager.GetString("x264Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $crf$ $profile$  --preset $preset$  $tune$  $userargs$   -o  &quot;$outputfile$&quot;  $input$.
        /// </summary>
        internal static string x265Line {
            get {
                return ResourceManager.GetString("x265Line", resourceCulture);
            }
        }
    }
}
