//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyx264CoderGUI {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Easyx264CoderGUI.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 SetWorkingDir(&quot;$avisynth_plugin$&quot;)
        ///LoadPlugin(&quot;ffms2.dll&quot;)     #加载FFmpegSource挂载方式
        ///LoadPlugin(&quot;LSMASHSource.dll&quot;) #LWLibavVideoSource挂载方式
        ///#LWLibavVideoSource(&quot;$InputVedio$&quot;)
        ///FFVideoSource(&quot;$InputVedio$&quot;)
        ///ChangeFPS(25)
        ///ConvertToYV12() 的本地化字符串。
        /// </summary>
        internal static string Avs25fps {
            get {
                return ResourceManager.GetString("Avs25fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SetWorkingDir(&quot;$avisynth_plugin$&quot;)
        ///LoadPlugin(&quot;ffms2.dll&quot;)     #加载FFmpegSource挂载方式
        ///LoadPlugin(&quot;LSMASHSource.dll&quot;) #LWLibavVideoSource挂载方式
        ///LoadPlugin(&quot;VSFilter.dll&quot;)     #加载字幕插件
        ///Load_Stdcall_Plugin(&quot;yadif.dll&quot;)     #Yadif反交错滤镜
        ///LoadPlugin(&quot;nnedi3-0.9.4\nnedi3.dll&quot;)
        ///LoadPlugin(&quot;RemoveGrain-1.0\RemoveGrainSSE3.dll&quot;)
        ///LoadPlugin(&quot;RemoveGrain-1.0\RepairSSE3.dll&quot;)
        ///LoadPlugin(&quot;FluxSmooth-1.1a\FluxSmooth.dll&quot;)
        ///LoadPlugin(&quot;FFT3dGPU.dll&quot;)
        ///LoadPlugin(&quot;dither-1.23.0\avstp.dll&quot;)
        ///LoadPlugin(&quot;SmoothAdjust-v2.80\a [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AvsQTGMC {
            get {
                return ResourceManager.GetString("AvsQTGMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SetWorkingDir(&quot;$avspluginpath$&quot;)
        ///
        ///LoadPlugin(&quot;dither-1.23.0\avstp.dll&quot;)
        ///LoadPlugin(&quot;SmoothAdjust-v2.80\avs-2.6.x\x86\SmoothAdjust.dll&quot;)
        ///LoadPlugin(&quot;masktools-26-for-2.6alpha4\mt_masktools-26.dll&quot;)
        ///LoadPlugin(&quot;nnedi3-0.9.4\nnedi3.dll&quot;)
        ///Import(&quot;masktools-v2.0a48\masktools\LimitedSharpenFaster.avsi&quot;)
        ///Import(&quot;masktools-v2.0a48\masktools\mfToon-v0.54.avsi&quot;)
        ///Import(&quot;masktools-v2.0a48\masktools\vmToon-v0.74.avsi&quot;)
        ///LoadPlugin(&quot;dither-1.23.0\dither.dll&quot;)
        ///Import(&quot;dither-1.23.0\dither.avsi&quot;)
        ///Import(&quot;O16mod_ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AvsScriptTemplete {
            get {
                return ResourceManager.GetString("AvsScriptTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --demuxer lavf --input-range pc --range pc    --bframes 9 --qcomp 0.60  --direct auto  --me umh   --psy-rd 0.40:0.00  --aq-strength 0.8   的本地化字符串。
        /// </summary>
        internal static string TempleteGamei444 {
            get {
                return ResourceManager.GetString("TempleteGamei444", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --demuxer lavf  --qcomp 0.80 --direct auto  --me umh   --aq-strength 0.8  的本地化字符串。
        /// </summary>
        internal static string TempleteHDi420 {
            get {
                return ResourceManager.GetString("TempleteHDi420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --demuxer lavf  --no-mbtree 的本地化字符串。
        /// </summary>
        internal static string TempleteOnline {
            get {
                return ResourceManager.GetString("TempleteOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --output-csp $csp$ $profile$   $crf$  --preset $preset$  $tune$  $resize$    $userargs$   -o  $outputfile$ $input$ 的本地化字符串。
        /// </summary>
        internal static string x264Line {
            get {
                return ResourceManager.GetString("x264Line", resourceCulture);
            }
        }
    }
}
